#!/usr/bin/env bash
# Promote the six component repositories' committed `main` trees into the
# read-only mirrors at this repository's root, and record the exact source
# commits in COMPONENTS.yml.
#
# Maintainer layout: the live component repositories are mounted (gitignored)
# under dev/ — each is a full, independent git repository with its own origin
# and PR flow. Day-to-day changes land there; run this script when a
# component's main is stable, then review `git status` and commit the refresh
# through the usual PR flow. Mirrors are generated — never edit them directly.
#
# Usage: scripts/sync-components.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPONENTS=(ShipSmart-Web ShipSmart-Orchestrator ShipSmart-API ShipSmart-MCP ShipSmart-Infra ShipSmart-Test)
cd "$ROOT"

{
  echo "# Generated by scripts/sync-components.sh — do not edit by hand."
  echo "# Each mirror directory equals its component repo's main at the recorded commit."
  echo "synced_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "components:"
} > COMPONENTS.yml

for c in "${COMPONENTS[@]}"; do
  src="$ROOT/dev/$c"
  if [ ! -e "$src/.git" ]; then
    echo "error: live repo not found at dev/$c" >&2
    exit 1
  fi
  sha=$(git -C "$src" rev-parse main)
  short=$(git -C "$src" rev-parse --short main)
  subject=$(git -C "$src" log -1 --format=%s main)
  subject=${subject//\"/\\\"}
  rm -rf "${ROOT:?}/${c:?}"
  mkdir -p "$ROOT/$c"
  git -C "$src" archive main | tar -x -C "$ROOT/$c"
  {
    echo "  $c:"
    echo "    repo: https://github.com/nia194/$c"
    echo "    commit: $sha"
    echo "    subject: \"$subject\""
  } >> COMPONENTS.yml
  echo "synced $c @ $short"
done

echo "done — review 'git status', then commit the refresh through the usual PR flow."
